version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: django
    versions:
    - ">= 2.3, < 2.2"
  - dependency-name: djangorestframework
    versions:
    - ">= 3"
  - dependency-name: django-guid
    versions:
    - ">= 3"
  commit-message:
    prefix: "[noissue]"
