version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: django
    versions:
    - ">= 3.1.a, < 3.2"
  - dependency-name: django
    versions:
    - 3.0.11
    - 3.0.12
    - 3.0.13
    - 3.0.13
    - 3.0.14
    - 3.0.14
  - dependency-name: drf-spectacular
    versions:
    - 0.13.1
    - 0.13.2
    - 0.14.0
    - 0.15.0
  - dependency-name: djangorestframework
    versions:
    - 3.12.2
    - 3.12.3
  - dependency-name: django-lifecycle
    versions:
    - 0.8.1
    - 0.9.0
    - 0.9.1
  - dependency-name: drf-nested-routers
    versions:
    - 0.92.5
    - 0.93.3
  - dependency-name: drf-access-policy
    versions:
    - 0.8.6
    - 0.8.7
  - dependency-name: django-import-export
    versions:
    - 2.5.0
  - dependency-name: rq
    versions:
    - 1.7.0
  - dependency-name: django-currentuser
    versions:
    - 0.5.2
  - dependency-name: django-filter
    versions:
    - 2.4.0
  commit-message:
    prefix: "[noissue]"
